name=input("enter the name: ")
age=int(input('enter the age '))
address=input("your address")
contact=int(input("enter the number"))
email=input('ur email id ')
qualification=input("ur qualification")
exprience=input("enter your expertions")
print('............................BIO DATA.............................')
print(name)
print(age)
print(address)
print(contact)
print(email)
print(qualification)
print(exprience)

